name: Golang CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run build of the application
      - name: Run build
        run: go build .

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet ./... 
          golint ./...

      # Run testing on the code
      - name: Run testing
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
